[tool.poetry]
name = "innertube"
version = "0.1.0"
description = "Python Client for Google's Private InnerTube API. Works with Youtube, YouTubeMusic etc."
authors = ["Tom Bulled <26026015+tombulled@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tombulled/innertube"
repository = "https://github.com/tombulled/innertube"
keywords = ["youtube", "innertube"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.7.3"
requests = "^2.25.1"
beautifulsoup4 = "^4.9.3"
Babel = "^2.9.0"
addict = "^2.4.0"
furl = "^2.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
